version: '3'

services:

###> doctrine/doctrine-bundle ###
  database:
#    container_name: fbc_database
    image: mysql:8.3
    environment:
      - MYSQL_DATABASE=fbc
      - MYSQL_ROOT_PASSWORD=passwd
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
